FROM python:3.9.5-buster

COPY ./requirements.txt /requirements.txt

#RUN pip3 install --upgrade pip
#RUN pip3 install --upgrade setuptools
#RUN pip3 install -r requirements.txt

CMD ["ping","8.8.8.8"]