FROM ubuntu:20.04

COPY ./src /src

CMD ["/bin/sh","/src/init.sh"]

#WORKDIR /src
#
#RUN pip3 install --upgrade pip
#RUN pip3 install --upgrade setuptools
#RUN pip3 install -r requirements.txt
#
#CMD ["random_requester.py"]
#ENTRYPOINT ["python3"]